#!/bin/bash

target_dir=${1}
if [[ -z "${target_dir}" ]]; then
    echo "Please provide a target directory hierarchy to search for .github/workflows directories"
    exit 2
fi

# See https://man7.org/linux/man-pages/man1/find.1.html for the starting
# example this method was initially created.

# Human method of finding git repositories while skipping unnecessary
# directories.
find ${target_dir} \
    -type d \( \
        -name "node_modules" -o \
        -name "venv" -o \
        -name "__pycache__" -o \
        -name "build" -o \
        -name "dist" \
    \) -prune \
    -o -type d -exec test -d '{}/.git' -a -d '{}/.github/workflows' \; -print -prune | while read d; do ls -ld ${d}/.github/workflows; done

# The above is really slow because...
